# config/meta.yml

meta_product_name: "Breaking Out!"
meta_title: "Breaking Out! - 2D Escape Game"
meta_description: "Welcome to Breaking Out! - a two-dimensional escape game you'll be challenged to complete within a limited time..."
meta_image: "logo.png" # should exist in `app/assets/images/`
